version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "127.0.0.1:8080:8080/tcp"
    depends_on:
      - db
    env_file: ./env-var

  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    env_file: ./env-var